import type { Student } from '@/types';

export const students: Student[] = [
  { id: 1, name: 'Agung Ramaindra Syahputra' },
  { id: 2, name: 'Ainun Tiyas Martiningsih' },
  { id: 3, name: 'Alessia Alzena Riangga' },
  { id: 4, name: 'Almaira Faiqha' },
  { id: 5, name: 'Alya Faliha' },
  { id: 6, name: 'Amirah Julveni Maulana' },
  { id: 7, name: 'Andi Aqil' },
  { id: 8, name: 'Aurora Felicia Angelie' },
  { id: 9, name: 'Bilqis Melani' },
  { id: 10, name: 'Chaya Muja Syatira' },
  { id: 11, name: 'Fadhil Oktavian Nabil' },
  { id: 12, name: 'Fahmi Firjatullah' },
  { id: 13, name: 'Faiz Alfarizi' },
  { id: 14, name: 'Farhan Umaydillah Radjiansyah' },
  { id: 15, name: 'Fathir Pradipta Alfarizi' },
  { id: 16, name: 'Fazril Nizart' },
  { id: 17, name: 'Januari' },
  { id: 18, name: 'Jihaan Kaltsum Khairunnisa' },
  { id: 19, name: 'Juan Edra Abiya' },
  { id: 20, name: 'Khanza Rista Bhanuwati' },
  { id: 21, name: 'Kristiana Berta' },
  { id: 22, name: 'Marselino Prasetyo Wijaya' },
  { id: 23, name: 'M. Fadil Putra Pratama' },
  { id: 24, name: 'M. Kafka Adri Al-Maliq Sigmo' },
  { id: 25, name: 'M. Luthfi Faturrahman' },
  { id: 26, name: 'Natalis Fedora Purba' },
  { id: 27, name: 'Rafif Rakha Arkana Dih' },
  { id: 28, name: 'Rayhan Qolbu' },
  { id: 29, name: 'Runika Alzariva' },
  { id: 30, name: 'Suci Pratiwi' },
  { id: 31, name: 'Syafa Damia Sakhi' },
  { id: 32, name: 'Syech Faris Maulana' },
  { id: 33, name: 'Tegar Tri Pambudi' },
  { id: 34, name: 'Tersa Usela' },
  { id: 35, name: 'Tiara Husna Humairah' },
  { id: 36, name: 'Zhafira Mayarista' },
];

export const motivationalQuotes = [
  'Lautan tidak akan menjadi lautan jika tidak mengalami pasang surut. Tetaplah kuat!',
  'Seperti ombak yang tak pernah lelah, teruslah berusaha mencapai impianmu.',
  'Dalam kedalaman laut yang tenang, tersembunyi kekuatan yang luar biasa.',
  'Setiap ombak membawa pelajaran baru, belajarlah dari setiap pengalaman.',
  'Jadilah seperti bintang laut, selalu bersinar meski di dasar laut.',
  'Kesuksesan adalah perjalanan, bukan tujuan akhir. Terus berlayar!',
  'Seperti karang yang kokoh menghadapi ombak, tetaplah teguh dalam ujian.',
  'Air laut yang asin mengajarkan kita bahwa kehidupan penuh dengan rasa.',
  'Jangan takut terbenam, karena matahari akan terbit kembali.',
  'Keberanian adalah kemampuan untuk berenang melawan arus.',
];
